permalink   : /:title/
markdown    : kramdown
highlighter : pygments

paginate: 2 #6
comments: true
paginate_path: "/page/:num"

baseurl: "/nandomoreira-jekyll-theme" # change to empty string ""
domain_name: nandomoreira.me
google_analytics: UA-52446115-1

source:      source
destination: _site

# cover: /assets/images/header-cover.png

# site title, description, meta_description, meta_keywords
# Details for the RSS feed generator
name: BB8
title: My Blog
description: "Desenvolvedor Front-end/Wordpress, Design Responsivo, HTML5, CSS3 e JavaScript"
meta_description: "Desenvolvedor Front-end/Wordpress, Design Responsivo, HTML5, CSS3 e JavaScript"
meta_keywords: "site, website, loja virtual, lojas virtuais, e-commerce, wordpress, frontend, front-end, html5, css3, javascript, jquery, seo, otimizacao, performance"
url: http://nandomoreira.me
production_url: http://nandomoreira.me
repo: https://github.com/nandomoreirame/nandomoreira-jekyll-theme
disqus_shortname: "fernandomoreira"
rss_path: source/
author:
  name      : BB8
  image     : /assets/images/author.jpg
  email     : bb8@swars.com
  url       : http://bb8.me
  facebook  : http://facebook.com/bb8
  twitter   : http://twitter.com/bb8
  instagram : http://instagram.com/bb8
  github    : http://github.com/bb8
  linkedin  : http://linkedin.com/in/bb8
  bio       : I'm a big deal. 

# thought
# thought:
#   text: I have no special talent. I am only passionately curious.
#   author: Albert Einstein

# Plugin: jekyll-assets
assets:
  dirname: /assets
  baseurl: /nandomoreira-jekyll-theme/assets/ # change to /assets/
  sources:
    - assets/images
    - assets/fonts
    - assets/css
    - assets/js
  cache: true
  gzip: [ text/css, application/javascript ]

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  ignore:
    envs: all

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
